### ISSUE TITLE
Secret Manager Support Tasks Tracking

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#2176]
This thread will be used to track the tasks/feature requests associated with https://github.com/spring-cloud/spring-cloud-gcp/issues/2115 .

The tasks include:
- [x] Add Refdocs
- [x] Add Sample App
- [x] Enable Secret Manager on travis.
- [x] Verify that `@RefreshScope` works --- This doesn't work...
- [x] Add Secret Manager Template (if need is present)
- [x] Split code into separate module from autoconfig if template is added
- [ ] Consider [how to make property loading parallelized/non-blocking](https://github.com/spring-cloud/spring-cloud-gcp/pull/2168#discussion_r375371939)
- [x] Secret Manager should allow users to specify versions; [defaulting to "latest" is not a production best practice.](https://github.com/spring-cloud/spring-cloud-gcp/pull/2168#discussion_r375371939)

**Comment by dzou** [comment]
The tasks in this bug have all been completed (with the exception of the parallelized-loading feature).

Not 100% the parallel-loading idea is possible, I was doing some thinking and I think for this to work, there would need to be a way for the properties to be mapped to `ListenableFutures` and then the user to access these in a call-back oriented way. For now to keep things simple lets just keep things synchronous and revisit the async feature if demand for it emerges.
